### PR TITLE
Stats

### PR DESCRIPTION
**Pull request by sofiab97**
This depends on the server update.

### CODE REVIEW

**Comment by tchx84** [comment]
Note this can't be merged until we deploy recent Linka changes.

**Comment by melizeche** [comment]
@tchx84 any updates?

**Comment by tchx84** [comment]
@melizeche nope, but if @sofiab97 can no longer work on this I can pick it up.

**Comment by tchx84** [comment]
@melizeche just close it!

**Comment by melizeche** [comment]
Closed due inactivity

**Pull request closed without merging**
