### PR TITLE
get AQI measurement for the last 30 minutes

### PR DESCRIPTION
**Pull request by sofiab97**

### CODE REVIEW

**Comment by tchx84** [comment]
LGTM ! @melizeche

**Review by padiazg — CHANGES_REQUESTED** [review]
It would be better if you use `const` instead of `var`

**Comment by padiazg** [comment]
`var` declares a variable un the global scope, no matter if it was declared in a function. `const` and `let` declares variables in the local scope, so they will be visible only in the scope you define them, and those below it.

**Comment by sofiab97** [comment]
READY!

**Review by padiazg — APPROVED** [review]
LGTM

**Pull request merged**
